name: 'Get origin default branch'
description: 'The action dynamically pulls the default branch of a remote origin repository and outputs it.'
inputs:
  origin:  # id of input
    description: 'Owner/repo pair of the target repository.'
    required: true
    default: '${{ github.repository }}'
outputs:
  default_branch: # id of output
    description: 'This is the default branch of the target repository.'
runs:
  using: 'docker'
  image: 'Dockerfile'

# run npm init -y in the root folder of the repository