name: CI/CD pipeline

on:
  push:
    tags-ignore:
      - '**'
    paths:
      - 'src/index.js'
  pull_request:
    paths:
      - 'src/index.js'
  workflow_dispatch:

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm run restore

      - name: Lint the codebase
        run: |
          npm run lint

      - name: Build the codebase
        run: |
          npm run build

      - name: GHASC check
        uses: GeekMasher/advanced-security-compliance@v1.5
        with:
          policy-path: policies/security-policy.yml
          token: ${{ secrets.GHASC_TOKEN }} # token requires 'public_repo' and 'security_events' scopes